## 错误处理（一）

### panic! 不可恢复的错误

#### Rust 错误处理概述

* Rust的可靠性: 错误处理
    * 大部分情况下：在编译时提示错误，并处理
* 错误的分类
    * 可恢复
        * 例如文件未找到，可再次尝试
    * 不可恢复
        * bug，例如访问的索引超出范围
* Rust 没有类似异常的机制
    * 可恢复错误： Rust<T, E>
    * 不可恢复：panic！宏

#### 不可恢复的错误与panic!

* 当执行 panic! 宏时：
    * 程序会打印一个错误信息
    * 展开（unwind）、清理调用栈（stack）
    * 退出程序

#### 为应对panic，展开或终止（about）调用栈

* 默认情况下，当panic发生：
    * 程序会展开调用栈（工作量大）
        * Rust 沿着调用栈往回走
        * 清理每个遇到的函数中的数据
    * 或立即终止调用栈
        * 不进行清理，直接终止程序
        * 内存需要os进行清理
* 想让二进制文件更小，把设置从“展开” 改为 “终止”
    * 在cargo.toml中适当的profile部分设置：panic = ‘abort’
    * 如：
        ```
        // Cargo.toml
        # 生产环境中 程序如果发生panic,立即终止执行，稍后由操作系统回收资源
        [profile.release]
        panic = 'abort'
        ```
#### 代码示例：
1. 直接 panic!
```
fn main() {
    panic!("error and panic");
}
// thread 'main' panicked at 'error and panic', src/main.rs:2:5
// note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
2. 代码出错，程序内部调用panic!
```
fn main() {
    let v = vec![1,2,3,4];
    v[10];
}
// thread 'main' panicked at 'index out of bounds: the len is 4 but the index is 10', src/main.rs:4:5
// note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
// RUST_BACKTRACE=1 cargo run 可携带堆栈信息
```

#### 使用panic！产生的回缩信息
* 显示错误的堆栈信息
* panic! 可能出现在：
    * 业务代码中
    * 依赖代码中
* 可通过调用panic！的函数的回溯信息来定位引起问题的代码
* 通过设置环境变量RUST_BACKTRACE=1可得到堆栈信息
* 为了获取带有调试信息的回溯，必须启用调试符号（不带 --release）

#### 线上运行 携带参数方式
```
cargo run --release
```