## 错误处理（二）

### Result 与 可恢复的错误 (上)

大多数情况下，错误没有严重到停止整个应用程序的地步。Rust 里面可以使用Result枚举来处理失败的情况。

#### Result 枚举

* 定义
```
enum Result<T, E> {
    Ok(T),
    Err(E)
}
```
* T:操作成功情况下， ok 变体里返回的数据类型
* E: 操作失败情况下，Err变体里返回的错误类型。
* 如：
    ```
    fn main() {
        // f Result<File, Error>
    let f = File::open("hello.txt");
    }
    ```

#### 处理 Result 的一种方式：match 表达式

* 和 Option 枚举一样，Result及其变体也是由preflude 带入作用域。
* 如:
    ```
    use std::fs::File;
    fn main() {
        let f = File::open("hello.txt");
        let f = match f {
            Ok(file) => file,
            Err(err) => {
                panic!("open file error, {:?}", err);
            }
        };
    }
    // thread 'main' panicked at 'open file error, Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:8:12
stack backtrace:
   0: rust_begin_unwind
    ```

#### 匹配不同的错误

* 使用match处理
    ```
    use std::fs::File;

    fn main() {
        let f = File::open("hello.txt");
        let f = match f {
            Ok(file) => file,
            Err(error) => match error.kind() {
                std::io::ErrorKind::NotFound => match File::create("hello.txt") {
                    Ok(fc) => fc,
                    Err(e) => panic!("create hello.txt file failed, error:{:?}", e)
                }
                other_err => panic!("Error open file. errror:{:?}", other_err)
            }
        };
    }
    ```
* 闭包（clouse)。Result<T,E>有很多方法：
    * 他们接收闭包作为参数
    * 使用match实现。
    * 更简洁
    ```
    fn main() {
        let f = File::open("hello.txt").unwrap_or_else(|error| {
            if error.kind() == ErrorKind::NotFound {
                File::create("hello.txt").unwrap_or_else(|error| {
                    panic!("error  create  file: {:?}", error)
                })
            } else {
                panic!("error opening file, error:{:?}", error);
            }
        });
    }
    ```

#### unwrap

* unwrap: match 表达式的一个快捷方法：
    * 如果Result结果为ok，返回ok里面的值
    * 如果result结果为Err，调用panic!宏
    * 如：
    ```
    use std::{fs::File, io::ErrorKind};

    fn main() {
        let f = File::open("hello.txt");
        let f = File::open("hello.txt").unwrap();
    }
    // thread 'main' panicked at 'called `Result::unwrap()on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:12:37 
    stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
    ```
    * unwrap 错误信息不能自定义，需要自定义使用expect

#### expect
* expect： 和unwrap 类似，但可以指定错误信息
* 如：

```
fn main() {
    let f = File::open("hello.txt").expect("无法打开文件 hello.txt 文件");
}
thread 'main' panicked at '无法打开文件 hello.txt 文件: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:13:37
stack backtrace:
   0: rust_begin_unwind
        at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
    1: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
   2: core::option::expect_none_failed
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1234
   3: core::result::Result<T,E>::expect
             at /Users/lucky/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:933
   4: base_learn09_01::main
             at ./src/main.rs:13
   5: core::ops::function::FnOnce::call_once
             at /Users/lucky/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```